### ISSUE TITLE
Use a mock Fetcher in the typeIndexHelper test

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/soukai-solid-utils#17]

**Comment by michielbdejong** [comment]
It's now using the actual internet to fetch the example profile

**Comment by michielbdejong** [comment]
Also: test all the failure modes

**Comment by itsrezasoltani** [comment]
@michielbdejong 
[Link to implementation](https://github.com/pondersource/soukai-solid-utils/blob/af9190b0e639db7cf876b2dac4b663da7cfe6a00/test/unit/typeIndexHelpers.test.ts#L24-L25)
