### ISSUE TITLE
use [instance/instanceContaner] to get documents from typeIndex

### ISSUE THREAD

**Issue by soltanireza65** [pondersource/soukai-solid-utils#6]
will be solved after Noel De Martin fix this issue https://github.com/NoelDeMartin/soukai-solid/issues/17

**Comment by itsrezasoltani** [comment]
now we have instance URLs from typeIndex

[Link to implementation](https://github.com/pondersource/soukai-solid-data-modules/blob/22d9691530726a654a8cf4d15aba743c3358bd79/src/modules/Bookmarks.ts#L72C30-L72C30)

**Comment by itsrezasoltani** [comment]
https://github.com/pondersource/soukai-solid-data-modules/blob/d4236fb5f599522c6b834fe1e2596df5f7f44c25/src/modules/Bookmarks.ts#L123
