### ISSUE TITLE
add id to bookmark dm and timestamps

### ISSUE THREAD

**Issue by soltanireza65** [pondersource/soukai-solid-utils#7]
the id should be in uuid shape

**Comment by itsrezasoltani** [comment]
https://github.com/NoelDeMartin/soukai-solid#primary-keys

**Comment by itsrezasoltani** [comment]
id field added:
[Link to implementation](https://github.com/pondersource/soukai-solid-data-modules/blob/75cb1707e28f6bf9d5d5f66c3a5fa274cf899351/src/modules/Bookmarks.ts#L147C12-L147C12)

**Comment by itsrezasoltani** [comment]
timestamps added
[Link to implementation](https://github.com/pondersource/soukai-solid-data-modules/blob/acedbca4bb90dd2b4329f0bb44f0b4726321687f/src/modules/Bookmarks.ts)
